version: '3.8'

services:
  finbert-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_WORKERS=1
      - API_RELOAD=false
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - LOG_FORMAT=json
    env_file:
      - .env
    volumes:
      - model_cache:/app/.cache
      - app_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - finbert-api
    restart: unless-stopped
    profiles:
      - nginx

volumes:
  model_cache:
    driver: local
  app_logs:
    driver: local